### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by pedromtavares** [deanpcmad/omniauth-discord#1]
Hey man,

First of all thanks for taking the initiative to make this gem!

I keep getting these Authentication Failures, you have any idea what could be causing them? I've tried quite a few things including changing my app secret, kind of ran out of options here, hehe. I am using other Omniauth providers btw so it's probably not something related to the gem itself.

Any help would be appreciated, here's the stack trace:

```
Started GET "/auth/discord" for 127.0.0.1 at 2016-07-02 04:30:59 -0300
I, [2016-07-02T04:30:59.658354 #46380]  INFO -- omniauth: (discord) Request phase initiated.

Started GET "/auth/discord/callback?state=d33ffea3855f9de566c83306159e799195bb694feb3c2c62&code=nrQbDuErRE2Vx0XncXEOlvogsCWFcK" for 127.0.0.1 at 2016-07-02 04:31:02 -0300
I, [2016-07-02T04:31:02.817329 #46380]  INFO -- omniauth: (discord) Callback phase initiated.
E, [2016-07-02T04:31:03.695007 #46380] ERROR -- omniauth: (discord) Authentication failure! invalid_credentials: OAuth2::Error, <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Update: I just tried setting my app secret to a dummy string 'foo' and the error was different:

```
ERROR -- omniauth: (discord) Authentication failure! invalid_credentials: OAuth2::Error, invalid_client:
{"error": "invalid_client"}
```

**Comment by adaoraul** [comment]
Hello Pedro,

I'm working on this issue right now and we'll have some update today.

**Comment by adaoraul** [comment]
Issue fixed and closed! Thanks to @p2k!
