### ISSUE TITLE
{"code": 0, "message": "401: Unauthorized"}

### ISSUE THREAD

**Issue by Deekor** [deanpcmad/omniauth-discord#11]
Assuming it has to do with #3?

I'm at a loss because if I log into discord and under settings look at my authorized apps it's in there...

![screen shot 2017-08-27 at 4 00 00 pm](https://user-images.githubusercontent.com/1904267/29754401-69598110-8b41-11e7-9cf6-60c2b68571f1.png)

**Comment by Grafikart** [comment]
What scope did you use ?

**Comment by smlparry** [comment]
I was also having this error when requesting just `scope: "bot"` 

Updating the `scope` to `"identify bot"` fixed this for me 👌

**Comment by adaoraul** [comment]
@smlparry do you have your configuration like these above?

<img width="1009" alt="screen shot 2019-03-06 at 8 23 22 am" src="https://user-images.githubusercontent.com/87910/53863035-640cc880-3fe9-11e9-921c-43d7a09e8912.png">
<img width="1004" alt="screen shot 2019-03-06 at 8 23 46 am" src="https://user-images.githubusercontent.com/87910/53863036-640cc880-3fe9-11e9-9362-e04611935824.png">
