### ISSUE TITLE
{"code": 0, "message": "401: Unauthorized"} Invalid credentials appears for SOME users

### ISSUE THREAD

**Issue by EricPickup** [deanpcmad/omniauth-discord#19]
I'm getting a 401 (unauthorized, invalid credentials) error only for certain users signing in through Discord. It was happening to me a while ago and is happening to several other users now. It's strange since it's still working fine at the same time for others.

The only scope I'm using is `guilds.join` and removing this seems to fix the issue however I need to use this scope.

I've checked the API keys many times and tried regenerating them without luck.

You can see my project/settings here: https://github.com/EricPickup/uwindsor-css-hub/blob/master/config/application.rb#L28

Full stack trace:
```
I, [2019-05-08T01:17:37.441229 #15559]  INFO -- omniauth: (discord) Callback phase initiated.
E, [2019-05-08T01:17:37.768887 #15559] ERROR -- omniauth: (discord) Authentication failure! invalid_credentials: OAuth2::Error, :
{"code": 0, "message": "401: Unauthorized"}

OAuth2::Error (:
{"code": 0, "message": "401: Unauthorized"}):

oauth2 (1.4.1) lib/oauth2/client.rb:119:in `request'
oauth2 (1.4.1) lib/oauth2/access_token.rb:107:in `request'
oauth2 (1.4.1) lib/oauth2/access_token.rb:114:in `get'
omniauth-discord (1.0.0) lib/omniauth/strategies/discord.rb:34:in `raw_info'
omniauth-discord (1.0.0) lib/omniauth/strategies/discord.rb:17:in `block in <class:Discord>'
omniauth (1.9.0) lib/omniauth/strategy.rb:109:in `instance_eval'
omniauth (1.9.0) lib/omniauth/strategy.rb:109:in `block in compile_stack'
omniauth (1.9.0) lib/omniauth/strategy.rb:108:in `each'
omniauth (1.9.0) lib/omniauth/strategy.rb:108:in `inject'
omniauth (1.9.0) lib/omniauth/strategy.rb:108:in `compile_stack'
omniauth (1.9.0) lib/omniauth/strategy.rb:102:in `uid_stack'
omniauth (1.9.0) lib/omniauth/strategy.rb:332:in `uid'
omniauth (1.9.0) lib/omniauth/strategy.rb:348:in `auth_hash'
omniauth (1.9.0) lib/omniauth/strategy.rb:372:in `callback_phase'
omniauth-oauth2 (1.6.0) lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
omniauth (1.9.0) lib/omniauth/strategy.rb:238:in `callback_call'
omniauth (1.9.0) lib/omniauth/strategy.rb:189:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/builder.rb:64:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.7) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:22:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by EricPickup** [comment]
Hey @adaoraul, did you have a chance to look at this? I've triple checked all of my configuration and can't figure out the issue.

**Comment by tbhockey** [comment]
Bump. Any update here? I'm having the same issue.

**UPDATE**: Mmm actually i take that back. I get this error even if i remove the `guilds.join` scope.
**UDPATE 2**: Ok, so i actually had a couple scopes. When I remove them _both_ suddenly everything works properly again for all users. Definitely feels like a bug somewhere.

```
# Does not work
config.omniauth :discord, ENV["DISCORD_APP_ID"], ENV["DISCORD_APP_SECRET"], scope: 'email guilds.join'

# Does work
config.omniauth :discord, ENV["DISCORD_APP_ID"], ENV["DISCORD_APP_SECRET"]
```

**Comment by tbhockey** [comment]
@EricPickup i found a solution that worked for me, making me wonder if this isn't a bug in the Devise gem itself. ☝️

**Comment by adaoraul** [comment]
Hi @EricPickup and @tbhockey,

I've tested the gem and I couldn't find the error you both mentioned. Maybe it's related to another gem used in your projects.

In addition, I've created and example app in the project folder and you can use your own configuration and see if it's working.

For running the example you can use:

`DISCORD_CLIENT_ID=YOUR_KEY DISCORD_CLIENT_ID=YOUR_SECRET APP_SCOPE='YOUR_SCOPE puma` 

Try it and let me know about any error.

Thanks!

**Comment by tbhockey** [comment]
@adaoraul yea, upon stumbling into a solution that "fixed" this, I believe this must be a bug in Devise or the Devise gem. Sorry to have troubled you.

**Comment by adaoraul** [comment]
Thanks and sorry for the late reply.

**Comment by tbhockey** [comment]
@EricPickup do you have any update on this? I thought what I had suggested above fixed my issue, but turns out i think it just mislead me into thinking it fixed the issue. It seems I only run into this with a user who has _never_ authenticated with the app before. But I am indeed still running into this with certain users.

**Comment by EricPickup** [comment]
@tbhockey I never found a fix for it. I was seeing the same behavior - if a user authenticated before I added the `guilds.join` scope they would be fine using it afterwards. If a new user tried with the scope it always failed.

I ended up manually setting up authentication in my app.

**Comment by tbhockey** [comment]
That's exactly what i've been experiencing. OK.

**Comment by hcyildirim** [comment]
@tbhockey @EricPickup I'm experiencing that same weird behavior in my app, did you guys solve it somehow?

**Comment by tbhockey** [comment]
> @tbhockey @EricPickup I'm experiencing that same weird behavior in my app, did you guys solve it somehow?

Shoot, unfortunately i cannot remember anymore, but we are no longer experiencing this issue :(

**Comment by EricPickup** [comment]
I wasn't able to fix it. I also wasn't using Devise. I think the problem had to do with using multiple omniauth gems in the same app but I can't remember why.

I ended up building out my own solution for the Discord API since our needs were pretty simple.

**Comment by gracz21** [comment]
I was using some custom scopes selection and I have had the same issue. It seems it's not connected to the actual authentication, rather it seems to be caused by the next subsequent request to `GET/oauth2/@me`.

I fixed it by adding `identify` to the list of custom scopes so that the gem will be able to fetch the data of the user right after authenticating them.

**Comment by waymondo** [comment]
fwiw i ran into this and was confused as well. the callback from discord seemed correct yet the OAuth2 error was raised during the handling of the response.

since [this line](https://github.com/adaoraul/omniauth-discord/blob/main/lib/omniauth/strategies/discord.rb#L34) requires the `identity` scope to be listed, maybe it should be forced onto the scope param if not provided. what do you think @adaoraul? i don't mind opening a PR for that that sounds correct to you.
