### ISSUE TITLE
Keeps getting consent page after successful authorization

### ISSUE THREAD

**Issue by arfinastra** [deanpcmad/omniauth-discord#21]
Hello,

I've implemented in my Ruby on Rails app a normal `Authorization Code Grant` flow.
My problem is that, when any user logging in to Discord, get the consent page, and have to approve every time, when it's already approved.

What can cause this issue?

Thanks in advance

**Comment by adaoraul** [comment]
Hi @arfinastra,

Could you provide an example of the page is being shown and your omniauth-discord implementation?

Thanks!
