### ISSUE TITLE
how to check user.avatar.present?

### ISSUE THREAD

**Issue by yournumberone** [deanpcmad/omniauth-discord#29]
https://github.com/adaoraul/omniauth-discord/blob/b8d9789170c988250401c4c81b97cb90a0c0d1e1/lib/omniauth/strategies/discord.rb#L23
if user has not an avatar it saves only half of link

**Comment by seckenrode** [comment]
As a workaround, you can access `auth.extra["raw_info"]["avatar"]` which will contain the raw avatar hash from Discord.  You can use this to see if Discord gave you a `nil` value and handle this downstream in your application using that.
