### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by Catchpowle** [deanpcmad/omniauth-discord#3]
Possibly the same as previous issues, this error is thrown when the callback to my site is attempted.

`Started GET "/auth/discord/callback?state=09deee15983935f37fa62c3f191dfb5a9f8b79a276248a48&code=OfbkqeROJfh84LJMvs3U2yqDPWs3ak" for 127.0.0.1 at 2016-07-30 18:44:19 +0100
I, [2016-07-30T18:44:19.110439 #22180]  INFO -- omniauth: (discord) Callback phase initiated.
E, [2016-07-30T18:44:19.606038 #22180] ERROR -- omniauth: (discord) Authentication failure! invalid_credentials: OAuth2::Error, <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
`

**Comment by adaoraul** [comment]
Hi @Catchpowle,

Can you provide more information about your application?
Do you authorize the callback URL on your app?

**Comment by Catchpowle** [comment]
Thank you for getting back to me @adaoraul.
In my routes file I have `get '/auth/discord/callback', to: 'users#create'`

However in the omniauth.rb initializer I have:

```
OmniAuth.config.on_failure = proc do |env|
  SessionsController.action(:auth_failure).call(env)
end
```

This is the action it ends up in, I'm not sure if this answers your question, I'm happy to provide any more information.

**Comment by Catchpowle** [comment]
Update I've realised the version of the gem I was using wasn't the latest so I have now added gem 'omniauth-discord', '~> 0.1.2' to my gemfile and updated.

I'm now getting a different error, I believe it's the same as @depl0y was getting in https://github.com/adaoraul/omniauth-discord/issues/2.

`Started GET "/auth/discord/callback?state=9fffa1a52c169bdc38373fe652d982d9fba132fbbc8dade6&code=fm7oCO357B0qdHHlk9LJWXaJRnwknm" for 127.0.0.1 at 2016-07-31 12:17:54 +0100
I, [2016-07-31T12:17:54.736738 #17395]  INFO -- omniauth: (discord) Callback phase initiated.
E, [2016-07-31T12:17:55.157635 #17395] ERROR -- omniauth: (discord) Authentication failure! invalid_credentials: OAuth2::Error, : 
{"code": 0, "message": "401: Unauthorized"}
Processing by SessionsController#auth_failure as HTML
  Parameters: {"state"=>"9fffa1a52c169bdc38373fe652d982d9fba132fbbc8dade6", "code"=>"fm7oCO357B0qdHHlk9LJWXaJRnwknm"}
Redirected to http://localhost:3000/
`

**Comment by adaoraul** [comment]
Do you authorize your application URL on your Discord App, like the SS below?
![screen shot 2016-07-31 at 4 03 11 pm](https://cloud.githubusercontent.com/assets/87910/17278658/6258f82a-5738-11e6-8962-478b32c9157f.png)

**Comment by Catchpowle** [comment]
Ah I authorized this URL http://localhost:3000/auth/discord/callback.

I believe this part is correct, because if I change it to something erroneous I instead get taken to this error page when I attempt to authenticate. Instead I get taken to the auth_failure action within my app.

![auth_error](https://cloud.githubusercontent.com/assets/2227892/17278753/3191d06c-575c-11e6-81d5-c1e03608266a.png)

**Comment by adaoraul** [comment]
Hey @Catchpowle,

Can you please provide a sample application that reproduces the error?

Also, see my example and make sure you are doing the right configuration!

https://gist.github.com/adaoraul/45b938403318e6b17559335554a6c2e5
https://omniauth-discord.herokuapp.com/

**Comment by Catchpowle** [comment]
Hey @adaoraul 

I tried authenticating with your app and was unfortunately taken to an error page at the following URL:
`https://omniauth-discord.herokuapp.com/auth/failure?message=invalid_credentials&origin=https%3A%2F%2Fomniauth-discord.herokuapp.com%2F&strategy=discord`

![screenshot from 2016-08-01 09 54 33](https://cloud.githubusercontent.com/assets/2227892/17288707/4cfc097c-57ce-11e6-8edf-aea8b9e4dfea.png)

**Comment by Catchpowle** [comment]
I will provide a sample rails application with the problem when I'm home from work in the evening, it's 10am currently in the UK, UTC+1 for reference. Thank you for helping!

**Comment by adaoraul** [comment]
@Catchpowle 

The application show Not Found because i haven't implemented the Failure method, look again in the gist and heroku demo.

**Comment by Catchpowle** [comment]
I've tried the sample application with your credentials through the Heroku link and locally on my machine with my own apps credentials, both times I was taken to failure page below where you are outputting params[:message]:
![discord](https://cloud.githubusercontent.com/assets/2227892/17304129/f1401012-581b-11e6-8683-446e7e2d3bfb.png)

The output from Sinatra on my machine was as follows:

```

I, [2016-08-01T19:09:43.785842 #5002]  INFO -- omniauth: (discord) Callback phase initiated.
E, [2016-08-01T19:09:44.286452 #5002] ERROR -- omniauth: (discord) Authentication failure! invalid_credentials: OAuth2::Error, : 
{"code": 0, "message": "401: Unauthorized"}
127.0.0.1 - - [01/Aug/2016:19:09:44 +0100] "GET /auth/discord/callback?state=eb9f5f80fd86b7a4148a13be8e6ec40e59306f220298c8fe&code=TkVaPN71GrIVuG26fL1gIbH1HZlj5Q HTTP/1.1" 302 9 0.5018
localhost - - [01/Aug/2016:19:09:43 BST] "GET /auth/discord/callback?state=eb9f5f80fd86b7a4148a13be8e6ec40e59306f220298c8fe&code=TkVaPN71GrIVuG26fL1gIbH1HZlj5Q HTTP/1.1" 302 9
- -> /auth/discord/callback?state=eb9f5f80fd86b7a4148a13be8e6ec40e59306f220298c8fe&code=TkVaPN71GrIVuG26fL1gIbH1HZlj5Q
127.0.0.1 - - [01/Aug/2016:19:09:44 +0100] "GET /auth/failure?message=invalid_credentials&origin=http%3A%2F%2Flocalhost%3A4567%2F&strategy=discord HTTP/1.1" 200 30 0.0008
localhost - - [01/Aug/2016:19:09:44 BST] "GET /auth/failure?message=invalid_credentials&origin=http%3A%2F%2Flocalhost%3A4567%2F&strategy=discord HTTP/1.1" 200 30
- -> /auth/failure?message=invalid_credentials&origin=http%3A%2F%2Flocalhost%3A4567%2F&strategy=discord
```

Does the Heroku app work for you?

**Comment by adaoraul** [comment]
This error shows because you are using invalid credentials, it's not an application error!
Show me your application and I'll try help you.

**Comment by Catchpowle** [comment]
Okay will do, but the app hosted on Heroku uses your credentials so that should have worked right?

**Comment by Catchpowle** [comment]
Are you free to hop on a google hangout?

**Comment by Catchpowle** [comment]
Here's a test app with my demo apps credentials https://github.com/Catchpowle/test_omniauth_discord

**Comment by Catchpowle** [comment]
Here's the application:

![dis-app](https://cloud.githubusercontent.com/assets/2227892/17304682/a59ca8fc-581e-11e6-90f1-7f84127bcae5.png)

**Comment by Catchpowle** [comment]
Hey @adaoraul I've tried authenticating through your heroku app with multiple discord accounts on multiple machines and each attempt takes me to: 

![screenshot from 2016-08-02 12 45 30](https://cloud.githubusercontent.com/assets/2227892/17327323/099ef338-58af-11e6-91a8-38cdea676d93.png)

Does authenticating through https://omniauth-discord.herokuapp.com/ app definitely work for you? Thank you for taking the time to look at this.

**Comment by Catchpowle** [comment]
Hey @adaoraul have you had a chance to look at this?

**Comment by Catchpowle** [comment]
Hey @adaoraul I've done some more testing.

I think the error message the gem returns may be wrong as it appears I have authorized the app on discords end, even though I'm taken to the invalid credentials page when it returns to your heroku app.

![screenshot from 2016-08-05 09 02 28](https://cloud.githubusercontent.com/assets/2227892/17430372/b452dca2-5aeb-11e6-90e9-5bec1251d42f.png)

![screenshot from 2016-08-05 09 06 53](https://cloud.githubusercontent.com/assets/2227892/17430415/0143915a-5aec-11e6-99e0-48546be5d8ea.png)

Could it actually be succeeding, but there is an inaccurate error message being returned by the gem?

**Comment by wimhaanstra** [comment]
Hey @Catchpowle, thanks for picking this up. Didn't have time to supply any further details with the issue I created. Sorry @adaoraul.

As I am seeing it, you are receiving the same error message as me. One of the things I also tried was not using localhost:3000 as a host for my redirect url (deployed it to a server), but the same thing happened.

Not sure what is going wrong. Here is my application configuration also (reverted the redirect URL back to a local url).

The full callback url is : `http://lvg.pub:3000/users/auth/discord/callback`, which is correct as far as my routing goes.

![screen shot 2016-08-14 at 12 06 53](https://cloud.githubusercontent.com/assets/111713/17648489/a62ccfce-6217-11e6-9d5f-4b1bae42729d.png)

Also, this gem works: https://github.com/p2k/omniauth-discord

**Comment by adaoraul** [comment]
https://github.com/adaoraul/omniauth-discord/commit/48db6b1f97752efeecfca8a6038946b0b38860aa

**Comment by Catchpowle** [comment]
Thank you 48db6b1 fixed the issue for me.

**Comment by Deekor** [comment]
Hmm I'm getting the error a year later... running on `omniauth-discord (0.1.5)`

![screen shot 2017-08-27 at 4 00 00 pm](https://user-images.githubusercontent.com/1904267/29754368-d4291894-8b40-11e7-972f-11d133dc85ba.png)
