### ISSUE TITLE
Pull Request #5 is not live

### ISSUE THREAD

**Issue by omnilord** [deanpcmad/omniauth-discord#6]
The pull request to fix the scope override defect is not in a tagged version and isn't available through bundler.

**Comment by omnilord** [comment]
A temporary fix is to use this in the Gemfile:
`gem 'omniauth-discord', git: 'https://github.com/adaoraul/omniauth-discord', branch: 'master'`

**Comment by featheredtoast** [comment]
Can we get this one out? I'm in need of the identity + email scope, and am currently unable to request it from here.

**Comment by adaoraul** [comment]
Will be live today, sorry for the delay.
